# Generated by Django 3.2.9 on 2023-07-11 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='policies',
            options={'verbose_name_plural': 'Policies'},
        ),
        migrations.RenameField(
            model_name='productstatus',
            old_name='type',
            new_name='title',
        ),
    ]
